[project]
name = "mlget"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.0",
    "pytest>=8.4.2",
    "tqdm>=4.0",
]

[project.scripts]
mlget = "mlget.cli:main"
